modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/IronJetpacks/issues"
    modId="ironjetpacks"
    version="${mod_version}"
    displayName="Iron Jetpacks"
    updateJSONURL="https://api.blakesmods.com/v2/mods/ironjetpacks/1.21/updates"
    displayURL="https://blakesmods.com/iron-jetpacks"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="Tonius, Tomson124"
    description='''
    A fully customizable FE powered jetpacks mod!
    '''

    [[dependencies.ironjetpacks]]
        modId="neoforge"
        mandatory=true
        versionRange="[21.0.0-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.ironjetpacks]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.21,1.21.1)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.ironjetpacks]]
        modId="cucumber"
        mandatory=true
        versionRange="[7.0.1,)"
        ordering="NONE"
        side="BOTH"